# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.20.1
yarn_mappings=1.20.1+build.10
loader_version=0.19.5
loom_version=1.17-SNAPSHOT

# Mod Properties
malilib_version = 0.16.0
litematica_version=1.20.1-0.15.4
litematica_modrinth_version = 1ZTpW1lr
minecraft_version_out = 1.20.1
version=0.0.1-1.20.1
group=net.lucy

# Dependencies
fabric_api_version=0.92.12+1.20.1
mod_menu_version = 7.0.1
