package net.lucy.data;

import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Which blocks generate in which biomes. GENERATED by generate_biome_blocks.py from
 * Minecraft's own worldgen data -- edit the script or re-run it for another version,
 * don't edit this by hand. See that script for exactly what it does and doesn't cover.
 *
 * Most blocks (iron, diamond, coal, stone, dirt, ...) generate in nearly every biome of
 * their dimension, so which biome you're in makes no difference to finding them; those
 * are 'universal'. Only the rest have a list of biomes worth travelling to.
 */
public class BiomeBlocks {
    /** Blocks found in (nearly) every biome of a dimension: block -> dimension. */
    private static final Map<String, String> UNIVERSAL = new HashMap<>();
    /** Blocks that only generate in certain biomes: block -> those biomes. */
    private static final Map<String, List<String>> SPECIFIC = new HashMap<>();
    /** Blocks with a plentiful home in specific biomes that ALSO turn up in small patches almost
     *  everywhere in their dimension (sand, clay, gravel): block -> dimension. */
    private static final Map<String, String> ALSO_EVERYWHERE = new HashMap<>();
    /** Biome -> dimension (overworld, the_nether, the_end). */
    private static final Map<String, String> BIOME_DIMENSION = new HashMap<>();

    private static final List<String> SET_0 = List.of("badlands", "bamboo_jungle", "basalt_deltas", "beach", "birch_forest", "cold_ocean", "crimson_forest", "dark_forest", "deep_cold_ocean", "deep_dark", "deep_frozen_ocean", "deep_lukewarm_ocean", "deep_ocean", "desert", "dripstone_caves", "eroded_badlands", "flower_forest", "forest", "frozen_ocean", "frozen_river", "ice_spikes", "jungle", "lukewarm_ocean", "mushroom_fields", "nether_wastes", "ocean", "old_growth_birch_forest", "old_growth_pine_taiga", "old_growth_spruce_taiga", "plains", "river", "savanna", "savanna_plateau", "snowy_beach", "snowy_plains", "snowy_taiga", "sparse_jungle", "stony_shore", "sunflower_plains", "swamp", "taiga", "warm_ocean", "warped_forest", "windswept_forest", "windswept_gravelly_hills", "windswept_hills", "windswept_savanna", "wooded_badlands");
    private static final List<String> SET_1 = List.of("badlands", "desert", "eroded_badlands", "mangrove_swamp", "old_growth_pine_taiga", "old_growth_spruce_taiga", "swamp", "wooded_badlands");
    private static final List<String> SET_2 = List.of("badlands", "desert", "eroded_badlands", "wooded_badlands");
    private static final List<String> SET_3 = List.of("bamboo_jungle", "cold_ocean", "dark_forest", "deep_cold_ocean", "deep_dark", "deep_frozen_ocean", "deep_lukewarm_ocean", "deep_ocean", "dripstone_caves", "flower_forest", "forest", "frozen_ocean", "frozen_river", "jungle", "lukewarm_ocean", "lush_caves", "meadow", "ocean", "plains", "river", "savanna", "savanna_plateau", "sparse_jungle", "sunflower_plains", "swamp", "warm_ocean", "windswept_forest", "windswept_gravelly_hills", "windswept_hills", "windswept_savanna", "wooded_badlands");
    private static final List<String> SET_4 = List.of("bamboo_jungle", "beach", "birch_forest", "cold_ocean", "dark_forest", "deep_cold_ocean", "deep_dark", "deep_frozen_ocean", "deep_lukewarm_ocean", "deep_ocean", "desert", "dripstone_caves", "flower_forest", "forest", "frozen_ocean", "frozen_river", "ice_spikes", "jungle", "lukewarm_ocean", "meadow", "ocean", "old_growth_birch_forest", "old_growth_pine_taiga", "old_growth_spruce_taiga", "plains", "river", "savanna", "savanna_plateau", "snowy_beach", "snowy_plains", "snowy_taiga", "sparse_jungle", "stony_shore", "sunflower_plains", "taiga", "warm_ocean", "windswept_forest", "windswept_gravelly_hills", "windswept_hills", "windswept_savanna");
    private static final List<String> SET_5 = List.of("bamboo_jungle", "jungle", "sparse_jungle");
    private static final List<String> SET_6 = List.of("bamboo_jungle", "cold_ocean", "dark_forest", "deep_cold_ocean", "deep_dark", "deep_frozen_ocean", "deep_lukewarm_ocean", "deep_ocean", "dripstone_caves", "flower_forest", "forest", "frozen_ocean", "frozen_river", "jungle", "lukewarm_ocean", "meadow", "ocean", "plains", "river", "savanna", "savanna_plateau", "sparse_jungle", "sunflower_plains", "swamp", "warm_ocean", "windswept_forest", "windswept_gravelly_hills", "windswept_hills", "windswept_savanna", "wooded_badlands");
    private static final List<String> SET_7 = List.of("bamboo_jungle", "jungle", "old_growth_pine_taiga", "old_growth_spruce_taiga", "snowy_taiga", "sparse_jungle", "taiga");
    private static final List<String> SET_8 = List.of("basalt_deltas");
    private static final List<String> SET_9 = List.of("basalt_deltas", "nether_wastes", "soul_sand_valley", "warped_forest");
    private static final List<String> SET_10 = List.of("birch_forest", "dark_forest", "flower_forest", "forest", "meadow", "old_growth_birch_forest");
    private static final List<String> SET_11 = List.of("birch_forest", "dark_forest", "flower_forest", "forest", "old_growth_birch_forest");
    private static final List<String> SET_12 = List.of("cherry_grove", "deep_dark", "dripstone_caves", "lush_caves", "meadow", "plains", "savanna", "savanna_plateau", "sunflower_plains");
    private static final List<String> SET_13 = List.of("cherry_grove");
    private static final List<String> SET_14 = List.of("cherry_grove", "frozen_peaks", "grove", "jagged_peaks", "meadow", "snowy_slopes", "stony_peaks", "windswept_forest", "windswept_gravelly_hills", "windswept_hills");
    private static final List<String> SET_15 = List.of("cold_ocean", "deep_cold_ocean", "deep_lukewarm_ocean", "deep_ocean", "ocean");
    private static final List<String> SET_16 = List.of("crimson_forest");
    private static final List<String> SET_17 = List.of("crimson_forest", "soul_sand_valley", "warped_forest");
    private static final List<String> SET_18 = List.of("crimson_forest", "warped_forest");
    private static final List<String> SET_19 = List.of("dark_forest", "mushroom_fields");
    private static final List<String> SET_20 = List.of("dark_forest");
    private static final List<String> SET_21 = List.of("deep_dark", "dripstone_caves", "flower_forest", "plains", "sunflower_plains");
    private static final List<String> SET_22 = List.of("deep_dark", "dripstone_caves", "flower_forest", "meadow", "plains", "sunflower_plains");
    private static final List<String> SET_23 = List.of("deep_frozen_ocean", "frozen_ocean", "frozen_peaks");
    private static final List<String> SET_24 = List.of("deep_frozen_ocean", "frozen_ocean");
    private static final List<String> SET_25 = List.of("flower_forest", "meadow");
    private static final List<String> SET_26 = List.of("grove", "ice_spikes", "old_growth_pine_taiga", "old_growth_spruce_taiga", "snowy_plains", "snowy_taiga", "taiga", "windswept_forest", "windswept_gravelly_hills", "windswept_hills");
    private static final List<String> SET_27 = List.of("lush_caves");
    private static final List<String> SET_28 = List.of("lush_caves", "mangrove_swamp");
    private static final List<String> SET_29 = List.of("mangrove_swamp");
    private static final List<String> SET_30 = List.of("mangrove_swamp", "swamp");
    private static final List<String> SET_31 = List.of("old_growth_pine_taiga", "old_growth_spruce_taiga", "snowy_taiga", "taiga");
    private static final List<String> SET_32 = List.of("old_growth_pine_taiga", "old_growth_spruce_taiga");
    private static final List<String> SET_33 = List.of("savanna", "savanna_plateau", "windswept_savanna");
    private static final List<String> SET_34 = List.of("nether_wastes", "soul_sand_valley");
    private static final List<String> SET_35 = List.of("sunflower_plains");
    private static final List<String> SET_36 = List.of("swamp");
    private static final List<String> SET_37 = List.of("warped_forest");
    private static final List<String> SET_38 = List.of("old_growth_pine_taiga", "old_growth_spruce_taiga", "windswept_savanna", "wooded_badlands");
    private static final List<String> SET_39 = List.of("badlands", "eroded_badlands", "wooded_badlands");
    private static final List<String> SET_40 = List.of("frozen_peaks", "grove", "ice_spikes", "jagged_peaks", "snowy_slopes");
    private static final List<String> SET_41 = List.of("grove", "snowy_slopes");
    private static final List<String> SET_42 = List.of("beach", "deep_lukewarm_ocean", "desert", "lukewarm_ocean", "snowy_beach", "warm_ocean");
    private static final List<String> SET_43 = List.of("mushroom_fields");
    private static final List<String> SET_44 = List.of("soul_sand_valley");

    static {
        UNIVERSAL.put("air", "overworld");
        UNIVERSAL.put("amethyst_block", "overworld");
        UNIVERSAL.put("amethyst_cluster", "overworld");
        UNIVERSAL.put("ancient_debris", "the_nether");
        UNIVERSAL.put("andesite", "overworld");
        UNIVERSAL.put("bedrock", "overworld");
        UNIVERSAL.put("blackstone", "the_nether");
        UNIVERSAL.put("budding_amethyst", "overworld");
        UNIVERSAL.put("calcite", "overworld");
        UNIVERSAL.put("coal_ore", "overworld");
        UNIVERSAL.put("copper_ore", "overworld");
        UNIVERSAL.put("deepslate", "overworld");
        UNIVERSAL.put("deepslate_coal_ore", "overworld");
        UNIVERSAL.put("deepslate_copper_ore", "overworld");
        UNIVERSAL.put("deepslate_diamond_ore", "overworld");
        UNIVERSAL.put("deepslate_gold_ore", "overworld");
        UNIVERSAL.put("deepslate_iron_ore", "overworld");
        UNIVERSAL.put("deepslate_lapis_ore", "overworld");
        UNIVERSAL.put("deepslate_redstone_ore", "overworld");
        UNIVERSAL.put("diamond_ore", "overworld");
        UNIVERSAL.put("diorite", "overworld");
        UNIVERSAL.put("dirt", "overworld");
        UNIVERSAL.put("end_stone", "the_end");
        UNIVERSAL.put("fire", "the_nether");
        UNIVERSAL.put("gold_ore", "overworld");
        UNIVERSAL.put("granite", "overworld");
        UNIVERSAL.put("grass", "overworld");
        UNIVERSAL.put("grass_block", "overworld");
        UNIVERSAL.put("gravel", "overworld");
        UNIVERSAL.put("iron_ore", "overworld");
        UNIVERSAL.put("lapis_ore", "overworld");
        UNIVERSAL.put("large_amethyst_bud", "overworld");
        UNIVERSAL.put("lava", "overworld");
        UNIVERSAL.put("magma_block", "the_nether");
        UNIVERSAL.put("medium_amethyst_bud", "overworld");
        UNIVERSAL.put("nether_gold_ore", "the_nether");
        UNIVERSAL.put("nether_quartz_ore", "the_nether");
        UNIVERSAL.put("netherrack", "the_nether");
        UNIVERSAL.put("pumpkin", "overworld");
        UNIVERSAL.put("redstone_ore", "overworld");
        UNIVERSAL.put("small_amethyst_bud", "overworld");
        UNIVERSAL.put("smooth_basalt", "overworld");
        UNIVERSAL.put("stone", "overworld");
        UNIVERSAL.put("sugar_cane", "overworld");
        UNIVERSAL.put("tuff", "overworld");
        UNIVERSAL.put("water", "overworld");

        SPECIFIC.put("acacia_leaves", SET_33);
        SPECIFIC.put("acacia_log", SET_33);
        SPECIFIC.put("allium", SET_25);
        SPECIFIC.put("azalea", SET_27);
        SPECIFIC.put("azalea_leaves", SET_27);
        SPECIFIC.put("azure_bluet", SET_22);
        SPECIFIC.put("basalt", SET_8);
        SPECIFIC.put("big_dripleaf", SET_27);
        SPECIFIC.put("big_dripleaf_stem", SET_27);
        SPECIFIC.put("birch_leaves", SET_10);
        SPECIFIC.put("birch_log", SET_10);
        SPECIFIC.put("blue_ice", SET_24);
        SPECIFIC.put("blue_orchid", SET_36);
        SPECIFIC.put("brown_mushroom", SET_0);
        SPECIFIC.put("brown_mushroom_block", SET_19);
        SPECIFIC.put("brown_terracotta", SET_39);
        SPECIFIC.put("cactus", SET_2);
        SPECIFIC.put("cave_vines", SET_27);
        SPECIFIC.put("cave_vines_plant", SET_27);
        SPECIFIC.put("cherry_leaves", SET_13);
        SPECIFIC.put("cherry_log", SET_13);
        SPECIFIC.put("clay", SET_27);
        SPECIFIC.put("coarse_dirt", SET_38);
        SPECIFIC.put("cornflower", SET_22);
        SPECIFIC.put("crimson_fungus", SET_18);
        SPECIFIC.put("crimson_nylium", SET_16);
        SPECIFIC.put("crimson_roots", SET_17);
        SPECIFIC.put("crimson_stem", SET_16);
        SPECIFIC.put("dandelion", SET_4);
        SPECIFIC.put("dark_oak_leaves", SET_20);
        SPECIFIC.put("dark_oak_log", SET_20);
        SPECIFIC.put("dead_bush", SET_1);
        SPECIFIC.put("deepslate_emerald_ore", SET_14);
        SPECIFIC.put("emerald_ore", SET_14);
        SPECIFIC.put("fern", SET_7);
        SPECIFIC.put("flowering_azalea", SET_27);
        SPECIFIC.put("flowering_azalea_leaves", SET_27);
        SPECIFIC.put("hanging_roots", SET_27);
        SPECIFIC.put("ice", SET_23);
        SPECIFIC.put("infested_deepslate", SET_14);
        SPECIFIC.put("infested_stone", SET_14);
        SPECIFIC.put("jungle_leaves", SET_5);
        SPECIFIC.put("jungle_log", SET_5);
        SPECIFIC.put("large_fern", SET_31);
        SPECIFIC.put("light_gray_terracotta", SET_39);
        SPECIFIC.put("lilac", SET_11);
        SPECIFIC.put("lily_of_the_valley", SET_11);
        SPECIFIC.put("lily_pad", SET_30);
        SPECIFIC.put("mangrove_leaves", SET_29);
        SPECIFIC.put("mangrove_log", SET_29);
        SPECIFIC.put("mangrove_propagule", SET_29);
        SPECIFIC.put("mangrove_roots", SET_29);
        SPECIFIC.put("melon", SET_5);
        SPECIFIC.put("moss_block", SET_27);
        SPECIFIC.put("moss_carpet", SET_28);
        SPECIFIC.put("mossy_cobblestone", SET_32);
        SPECIFIC.put("mud", SET_29);
        SPECIFIC.put("muddy_mangrove_roots", SET_29);
        SPECIFIC.put("mushroom_stem", SET_19);
        SPECIFIC.put("mycelium", SET_43);
        SPECIFIC.put("nether_sprouts", SET_37);
        SPECIFIC.put("nether_wart_block", SET_16);
        SPECIFIC.put("oak_leaves", SET_6);
        SPECIFIC.put("oak_log", SET_3);
        SPECIFIC.put("orange_terracotta", SET_39);
        SPECIFIC.put("orange_tulip", SET_21);
        SPECIFIC.put("oxeye_daisy", SET_22);
        SPECIFIC.put("packed_ice", SET_23);
        SPECIFIC.put("peony", SET_11);
        SPECIFIC.put("pink_petals", SET_13);
        SPECIFIC.put("pink_tulip", SET_21);
        SPECIFIC.put("podzol", SET_32);
        SPECIFIC.put("poppy", SET_4);
        SPECIFIC.put("powder_snow", SET_41);
        SPECIFIC.put("red_mushroom", SET_0);
        SPECIFIC.put("red_mushroom_block", SET_19);
        SPECIFIC.put("red_sand", SET_39);
        SPECIFIC.put("red_sandstone", SET_39);
        SPECIFIC.put("red_terracotta", SET_39);
        SPECIFIC.put("red_tulip", SET_21);
        SPECIFIC.put("rooted_dirt", SET_27);
        SPECIFIC.put("rose_bush", SET_11);
        SPECIFIC.put("sand", SET_42);
        SPECIFIC.put("sandstone", SET_42);
        SPECIFIC.put("seagrass", SET_15);
        SPECIFIC.put("shroomlight", SET_18);
        SPECIFIC.put("small_dripleaf", SET_27);
        SPECIFIC.put("snow_block", SET_40);
        SPECIFIC.put("soul_fire", SET_9);
        SPECIFIC.put("soul_sand", SET_34);
        SPECIFIC.put("soul_soil", SET_44);
        SPECIFIC.put("spore_blossom", SET_27);
        SPECIFIC.put("spruce_leaves", SET_26);
        SPECIFIC.put("spruce_log", SET_26);
        SPECIFIC.put("sunflower", SET_35);
        SPECIFIC.put("sweet_berry_bush", SET_31);
        SPECIFIC.put("tall_grass", SET_12);
        SPECIFIC.put("terracotta", SET_39);
        SPECIFIC.put("warped_fungus", SET_18);
        SPECIFIC.put("warped_nylium", SET_37);
        SPECIFIC.put("warped_roots", SET_37);
        SPECIFIC.put("warped_stem", SET_37);
        SPECIFIC.put("warped_wart_block", SET_37);
        SPECIFIC.put("white_terracotta", SET_39);
        SPECIFIC.put("white_tulip", SET_21);
        SPECIFIC.put("yellow_terracotta", SET_39);

        ALSO_EVERYWHERE.put("clay", "overworld");
        ALSO_EVERYWHERE.put("gravel", "overworld");
        ALSO_EVERYWHERE.put("sand", "overworld");
        ALSO_EVERYWHERE.put("sandstone", "overworld");

        BIOME_DIMENSION.put("badlands", "overworld");
        BIOME_DIMENSION.put("bamboo_jungle", "overworld");
        BIOME_DIMENSION.put("basalt_deltas", "the_nether");
        BIOME_DIMENSION.put("beach", "overworld");
        BIOME_DIMENSION.put("birch_forest", "overworld");
        BIOME_DIMENSION.put("cherry_grove", "overworld");
        BIOME_DIMENSION.put("cold_ocean", "overworld");
        BIOME_DIMENSION.put("crimson_forest", "the_nether");
        BIOME_DIMENSION.put("dark_forest", "overworld");
        BIOME_DIMENSION.put("deep_cold_ocean", "overworld");
        BIOME_DIMENSION.put("deep_dark", "overworld");
        BIOME_DIMENSION.put("deep_frozen_ocean", "overworld");
        BIOME_DIMENSION.put("deep_lukewarm_ocean", "overworld");
        BIOME_DIMENSION.put("deep_ocean", "overworld");
        BIOME_DIMENSION.put("desert", "overworld");
        BIOME_DIMENSION.put("dripstone_caves", "overworld");
        BIOME_DIMENSION.put("end_barrens", "the_end");
        BIOME_DIMENSION.put("end_highlands", "the_end");
        BIOME_DIMENSION.put("end_midlands", "the_end");
        BIOME_DIMENSION.put("eroded_badlands", "overworld");
        BIOME_DIMENSION.put("flower_forest", "overworld");
        BIOME_DIMENSION.put("forest", "overworld");
        BIOME_DIMENSION.put("frozen_ocean", "overworld");
        BIOME_DIMENSION.put("frozen_peaks", "overworld");
        BIOME_DIMENSION.put("frozen_river", "overworld");
        BIOME_DIMENSION.put("grove", "overworld");
        BIOME_DIMENSION.put("ice_spikes", "overworld");
        BIOME_DIMENSION.put("jagged_peaks", "overworld");
        BIOME_DIMENSION.put("jungle", "overworld");
        BIOME_DIMENSION.put("lukewarm_ocean", "overworld");
        BIOME_DIMENSION.put("lush_caves", "overworld");
        BIOME_DIMENSION.put("mangrove_swamp", "overworld");
        BIOME_DIMENSION.put("meadow", "overworld");
        BIOME_DIMENSION.put("mushroom_fields", "overworld");
        BIOME_DIMENSION.put("nether_wastes", "the_nether");
        BIOME_DIMENSION.put("ocean", "overworld");
        BIOME_DIMENSION.put("old_growth_birch_forest", "overworld");
        BIOME_DIMENSION.put("old_growth_pine_taiga", "overworld");
        BIOME_DIMENSION.put("old_growth_spruce_taiga", "overworld");
        BIOME_DIMENSION.put("plains", "overworld");
        BIOME_DIMENSION.put("river", "overworld");
        BIOME_DIMENSION.put("savanna", "overworld");
        BIOME_DIMENSION.put("savanna_plateau", "overworld");
        BIOME_DIMENSION.put("small_end_islands", "the_end");
        BIOME_DIMENSION.put("snowy_beach", "overworld");
        BIOME_DIMENSION.put("snowy_plains", "overworld");
        BIOME_DIMENSION.put("snowy_slopes", "overworld");
        BIOME_DIMENSION.put("snowy_taiga", "overworld");
        BIOME_DIMENSION.put("soul_sand_valley", "the_nether");
        BIOME_DIMENSION.put("sparse_jungle", "overworld");
        BIOME_DIMENSION.put("stony_peaks", "overworld");
        BIOME_DIMENSION.put("stony_shore", "overworld");
        BIOME_DIMENSION.put("sunflower_plains", "overworld");
        BIOME_DIMENSION.put("swamp", "overworld");
        BIOME_DIMENSION.put("taiga", "overworld");
        BIOME_DIMENSION.put("the_end", "the_end");
        BIOME_DIMENSION.put("warm_ocean", "overworld");
        BIOME_DIMENSION.put("warped_forest", "the_nether");
        BIOME_DIMENSION.put("windswept_forest", "overworld");
        BIOME_DIMENSION.put("windswept_gravelly_hills", "overworld");
        BIOME_DIMENSION.put("windswept_hills", "overworld");
        BIOME_DIMENSION.put("windswept_savanna", "overworld");
        BIOME_DIMENSION.put("wooded_badlands", "overworld");
    }

    /** Does it generate in (nearly) every biome of its dimension, so biome doesn't matter? */
    public static boolean isUniversal(String block) { return UNIVERSAL.containsKey(block); }

    /** The biomes a block is limited to. Empty if it's universal, or not a generated block. */
    public static Set<String> biomesFor(String block) {
        List<String> biomes = SPECIFIC.get(block);
        return biomes == null ? Set.of() : new HashSet<>(biomes);
    }

    /** Does this block, though limited to certain biomes for real quantities, also turn up in
     *  small patches nearly everywhere? Then a small amount doesn't need a trip. */
    public static boolean isAlsoFoundEverywhere(String block) { return ALSO_EVERYWHERE.containsKey(block); }

    /** True if this dictionary knows anything about the block at all. */
    public static boolean isKnown(String block) { return UNIVERSAL.containsKey(block) || SPECIFIC.containsKey(block); }

    /** The dimension a biome belongs to, or null for one this doesn't classify (the_void). */
    public static String dimensionOf(String biome) { return BIOME_DIMENSION.get(biome); }
}