package net.lucy.data;

import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParser;

import java.io.IOException;
import java.io.InputStream;
import java.io.InputStreamReader;
import java.io.Reader;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;

/**
 * Which blocks generate in which biomes, loaded from biome_blocks.json.
 *
 * That file is GENERATED by generate_biome_blocks.py from Minecraft's own worldgen data --
 * edit the script and re-run it (for another version, or to fix something), don't hand-edit
 * the JSON. See that script for exactly what it does and doesn't cover.
 *
 * Most blocks (iron, diamond, coal, stone, dirt, ...) generate in nearly every biome of
 * their dimension, so which biome you're in makes no difference to finding them -- those
 * are "universal". Only the rest have a list of biomes actually worth travelling to.
 *
 * Missing the resource file isn't fatal: everything just reports as unknown/universal
 * rather than crashing the mod, the same as MiningData behaves when its file is absent.
 */
public final class BiomeData {
    private static final String RESOURCE_PATH = "/data/lazymaterialgathering/biome_blocks.json";
    private static final Map<String, String> UNIVERSAL;
    private static final Map<String, String> ALSO_EVERYWHERE;
    private static final Map<String, List<String>> SPECIFIC;
    private static final Map<String, String> BIOME_DIMENSION;
    static {
        LoadedData data = load();
        UNIVERSAL = Collections.unmodifiableMap(data.universal);
        ALSO_EVERYWHERE = Collections.unmodifiableMap(data.alsoEverywhere);
        SPECIFIC = Collections.unmodifiableMap(data.specific);
        BIOME_DIMENSION = Collections.unmodifiableMap(data.biomeDimension);
    }

    private BiomeData() {
    }

    /** Does it generate in (nearly) every biome of its dimension, so biome doesn't matter? */
    public static boolean isUniversal(String block) {
        return UNIVERSAL.containsKey(block);
    }

    /** The dimension a universal block generates in, or null if it isn't universal. */
    public static String getUniversalDimension(String block) {
        return UNIVERSAL.get(block);
    }

    /** The biomes a block is limited to. Empty if it's universal, or not a generated block at all. */
    public static Set<String> biomesFor(String block) {
        List<String> biomes = SPECIFIC.get(block);
        return biomes == null ? Set.of() : new HashSet<>(biomes);
    }

    /**
     * Does this block, though limited to certain biomes for real quantities, also turn up
     * in small patches nearly everywhere (sand, clay, gravel)? Then a small amount doesn't
     * need a special trip -- only a large one does.
     */
    public static boolean isAlsoFoundEverywhere(String block) {
        return ALSO_EVERYWHERE.containsKey(block);
    }

    /** True if this dictionary knows anything about the block at all. */
    public static boolean isKnown(String block) {
        return UNIVERSAL.containsKey(block) || SPECIFIC.containsKey(block);
    }

    /** The dimension a biome belongs to, or null for one this doesn't classify (the_void). */
    public static String dimensionOf(String biome) {
        return BIOME_DIMENSION.get(biome);
    }

    // ---------- Loading ----------

    private static final class LoadedData {
        final Map<String, String> universal;
        final Map<String, String> alsoEverywhere;
        final Map<String, List<String>> specific;
        final Map<String, String> biomeDimension;

        LoadedData(Map<String, String> universal, Map<String, String> alsoEverywhere, Map<String, List<String>> specific, Map<String, String> biomeDimension) {
            this.universal = universal;
            this.alsoEverywhere = alsoEverywhere;
            this.specific = specific;
            this.biomeDimension = biomeDimension;
        }
    }

    private static LoadedData load() {
        try (InputStream input = BiomeData.class.getResourceAsStream(RESOURCE_PATH)) {
            // Do not crash the whole mod if the optional static data file hasn't been installed yet.
            if (input == null) {
                return new LoadedData(new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>());
            }

            try (Reader reader = new InputStreamReader(input, StandardCharsets.UTF_8)) {
                JsonElement element = JsonParser.parseReader(reader);
                if (element.isJsonObject() == false) {
                    throw new IllegalStateException("Biome data root must be a JSON object");
                }

                JsonObject root = element.getAsJsonObject();
                return new LoadedData(loadStringMap(root, "universal"), loadStringMap(root, "alsoEverywhere"), loadListMap(root, "specific"), loadStringMap(root, "biomeDimension"));
            }
        }
        catch (IOException e) {
            throw new IllegalStateException("Failed to load biome data: " + RESOURCE_PATH, e);
        }
        catch (RuntimeException e) {
            throw new IllegalStateException("Invalid biome data: " + RESOURCE_PATH, e);
        }
    }

    private static Map<String, String> loadStringMap(JsonObject root, String field) {
        Map<String, String> result = new LinkedHashMap<>();
        JsonElement section = root.get(field);
        if (section == null || section.isJsonNull()) {
            return result;
        }
        if (section.isJsonObject() == false) {
            throw new IllegalStateException("'" + field + "' must be a JSON object");
        }

        for (Map.Entry<String, JsonElement> entry : section.getAsJsonObject().entrySet()) {
            result.put(entry.getKey(), entry.getValue().getAsString());
        }
        return result;
    }

    private static Map<String, List<String>> loadListMap(JsonObject root, String field) {
        Map<String, List<String>> result = new LinkedHashMap<>();
        JsonElement section = root.get(field);
        if (section == null || section.isJsonNull()) {
            return result;
        }
        if (section.isJsonObject() == false) {
            throw new IllegalStateException("'" + field + "' must be a JSON object");
        }

        for (Map.Entry<String, JsonElement> entry : section.getAsJsonObject().entrySet()) {
            List<String> biomes = new ArrayList<>();
            for (JsonElement biome : entry.getValue().getAsJsonArray()) {
                biomes.add(biome.getAsString());
            }
            result.put(entry.getKey(), biomes);
        }
        return result;
    }
}